spring:
  cloud:
    zookeeper:
      connect-string: zookeeper-1-dev.sofastack.tech:2181
      discovery:
        enabled: true
        instance-id: api-gateway
sofastack:
  auth:
    server:
      url: http://localhost:8033/login
management:
  endpoints:
    web:
      exposure:
        include: "*"